### ISSUE TITLE
Fix and improve SNR plugin

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stginga#73]
This is a follow-up of #72.
- [x] Turn minimum SBR limit into user preference (currently hardcoded at zero, which is pretty useless). Enable updating and logging it within `redo()`. Some thoughts need to go into this, as the limits can be quite operation/instrument specific.
- [x] Add option to only calculate using good pixels, both as user perference and GUI checkbox (like #38).
- [x] Add buttons to save/load parameter values (like #37).
- [x] Figure out whether ejeschke/ginga#266 is really an issue for this plugin or not (probably not if user can save parameters to JSON files).
- [x] Update example config file.
- [x] Add usage info and screenshot to `plugins.rst`

**Comment by pllim** [comment]
There is no good way to include SBR limits used by WSS as a general setting. I will just have to subclass `SBRCalc` and overwrite `set_minsbr()` method for WSS.
