### ISSUE TITLE
Interpolation/masking visualizer

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stginga#99]
As part of JWST DADF Sprint for background subtraction, there is a request for a local plugin to mark interpolation points and mask out unwanted data. Example:

![index](https://cloud.githubusercontent.com/assets/2090236/13579760/17337cdc-e46d-11e5-819e-2163453bc6f9.png)

To-do list:
- [x] Plugin to display marked points -- implemented in #101 
- [x] Plugin to display masks -- implemented in #103 
- [x] Plugin to draw masks -- implemented in ejeschke/ginga#292 (merged)

**Comment by pllim** [comment]
Technically, if you create a table with every masked pixels listed, and then choose to display that table in `TVMark` plugin as "points", you can effectively display the masks too...
